// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(ContactDetailContext))]
    partial class ContactDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.ContactDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("address3")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("city1")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("city2")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("city3")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cityPostalCode1")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("cityPostalCode2")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("cityPostalCode3")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("ContactDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
